### ISSUE TITLE
ERROR: repository docker.io/image_search not found: does not exist or no pull access

### ISSUE THREAD

**Issue by jimmybytes** [sethuiyer/Image-to-Image-search#19]
ERROR: repository docker.io/image_search not found: does not exist or no pull access

**Comment by jimmybytes** [comment]
### solved

modify `docker-compose.yaml`

> website.image need to fill in manually, after executing `docker_install.sh`, check `docker ps -a`,`${REPOSITORY}:${TAG}`

```bash
$ docker images
REPOSITORY                                                  TAG                 IMAGE ID            CREATED             SIZE
image_to_image_search                                       version2            7a10bc3d08cb        12 minutes ago      1.54 GB

# website.image = image_to_image_search:version2
```

```
version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node
  website:
    image: image_to_image_search:version2
    volumes:
      - ~/.keras:/root/.keras
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    working_dir: /image_search
    command: python3 server.py
```
